version: '3.1'

services:

  # api:
  #   image: animal-test
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "80:3000"
  #   environment:
  #     MONGODB_URI: mongodb://mongo:27017/Farms
  #     MONGODB_USER: root
  #     MONGODB_PASSWORD: esgi4ever
  #     PORT: 3000

  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  # for later:
  # grafana:
