version: '3.1'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/planade-zoo
      MONGODB_USER: root
      MONGODB_PASSWORD: root
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      - "6379:6379"
